import Egg.Core.Encode.Basic
import Egg.Core.Encode.EncodeM
import Egg.Core.Encode.Expression
import Egg.Core.Encode.IndexT
import Egg.Core.Basic
import Egg.Core.Config
import Egg.Core.Congr
import Egg.Core.Rewrites
import Egg.Tactic.Explanation.Parse
import Egg.Tactic.Explanation.Proof
import Egg.Tactic.Basic
import Egg.Tactic.Rewrites
import Egg.Tactic.Trace
